# Generated by Django 4.0.6 on 2023-03-03 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(max_length=60)),
                ('telefono', models.BigIntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inversion', models.BigIntegerField()),
                ('fechaIncio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('NomCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente')),
            ],
            options={
                'ordering': ('NomCliente',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='Administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inversor',
            field=models.BooleanField(default=True, verbose_name='Inversor'),
        ),
        migrations.CreateModel(
            name='valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesDia', models.CharField(max_length=10)),
                ('fechaDia', models.DateField()),
                ('SubTotal', models.CharField(max_length=100)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contrato')),
                ('usuarioValor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('contrato',),
            },
        ),
        migrations.CreateModel(
            name='retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRetiro', models.DateField()),
                ('valorRetiro', models.CharField(max_length=100)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contrato')),
                ('usuarioRetiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('contrato',),
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
