# Generated by Django 4.0.6 on 2023-03-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cliente_contrato_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retiro',
            name='usuarioRetiro',
        ),
        migrations.RemoveField(
            model_name='valores',
            name='usuarioValor',
        ),
    ]
