# Generated by Django 4.0.6 on 2023-03-03 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_retiro_usuarioretiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='NomCliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
    ]
