# Generated by Django 4.0.6 on 2023-03-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_cliente_usuario_alter_contrato_nomcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores',
            name='usuarioV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
