# Generated by Django 4.0.6 on 2023-03-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_valores_usuariov'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='usuarioC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
