# Generated by Django 4.0.6 on 2023-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contrato_usuarioc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valores',
            options={'ordering': ('fechaDia',)},
        ),
        migrations.AlterField(
            model_name='valores',
            name='SubTotal',
            field=models.BigIntegerField(),
        ),
    ]
