# Generated by Django 4.0.6 on 2023-03-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_valores_options_alter_valores_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='NomCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
    ]
