# Generated by Django 4.0.6 on 2023-03-07 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_contrato_nomcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='usuarioC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
