# Generated by Django 4.0.6 on 2023-03-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_contrato_usuarioc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
