# Generated by Django 4.0.6 on 2023-07-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_contrato_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='NomCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
        migrations.CreateModel(
            name='interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumainteres', models.CharField(max_length=10)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contrato')),
            ],
        ),
    ]
